-- EJECUTAR ESTA CONSULTA EN EL EDITOR DE SQL DE SUPABASE DASHBOARD
-- PARA AGREGAR LA COLUMNA DE PRIORIDAD A LA TABLA DE TICKETS DIRECTOS

ALTER TABLE tickets_directos ADD COLUMN IF NOT EXISTS prioridad TEXT DEFAULT 'Normal';
